---
- name: Install Apache and PHP
  apt:
    name:
      - apache2
      - php
      - php-mysql
      - php-sqlite3
      - php-mbstring
      - php-json
      - php-curl
      - php-xml
      - php-zip
      - php-intl
      - php-gd
      - libapache2-mod-php
    state: present

- name: Enable Apache modules
  apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - rewrite
    - ssl
    - headers
  notify: restart apache2

- name: Create SSL virtual host configuration
  template:
    src: ssl-vhost.conf.j2
    dest: "/etc/apache2/sites-available/{{ mail_domain }}-le-ssl.conf"
    owner: root
    group: root
    mode: '0644'
  notify: restart apache2

- name: Enable SSL site
  command: "a2ensite {{ mail_domain }}-le-ssl.conf"
  args:
    creates: "/etc/apache2/sites-enabled/{{ mail_domain }}-le-ssl.conf"
  notify: restart apache2

- name: Disable default Apache site
  command: a2dissite 000-default
  args:
    removes: /etc/apache2/sites-enabled/000-default.conf
  notify: restart apache2

- name: Start and enable Apache
  systemd:
    name: apache2
    state: started
    enabled: yes